name = "moe-counter-cf"
type = "javascript"
account_id = "4b07921748fd986e2000242245c50f21"
zone_id = "bU0sA1w1yi9HHcIEg-LfUT-B3gVspVr1OQxgfUhn"
workers_dev = false
route = "count.milik-fukada.eu.org/*"
compatibility_date = "2022-03-12"
kv_namespaces = [
  { binding = "KV", id = "4f164bc1c4444b1ab04755ff5261c3d5", preview_id = "4f164bc1c4444b1ab04755ff5261c3d5" },
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
